/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bmsprojectcs2a;

import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Alienware 15T 4k
 */
public class btnaccount extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(btnaccount.class.getName());

    /**
     * Creates new form Withdrawpage
     */
    long CN;
    public btnaccount(long CN) {
        initComponents();
        this.CN=CN;
    }

    private btnaccount() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BNtf = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        amounttf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        B_NAME = new javax.swing.JLabel();
        B_EMAIL = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        right = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WITHDRAW");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 80, 120));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(110, 148, 198));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go Back_1.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 630, 50, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Checkmark_1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, 50, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, -1, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 620, -1, 70));

        BNtf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(BNtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 460, 49));

        ok.setBackground(new java.awt.Color(44, 80, 120));
        ok.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ok.setForeground(new java.awt.Color(255, 255, 255));
        ok.setText("  ہاں                             Ok");
        ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ok.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel2.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, 250, 50));

        back.setBackground(new java.awt.Color(44, 80, 120));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back             پیچھے جائیں");
        back.setToolTipText("Go to Dashboard");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 630, 250, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter beneficiary account number:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Please enter  amount :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 240, -1));

        amounttf.setForeground(new java.awt.Color(153, 153, 153));
        amounttf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amounttfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                amounttfFocusLost(evt);
            }
        });
        jPanel2.add(amounttf, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 460, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("مستفید کے اکاؤنٹ نمبر درج کریں");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 460, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("بل کی رقم کا اندراج کریں");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 460, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Beneficiary's Name :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 360, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Beneficiary's Email :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 360, 50));

        B_NAME.setBackground(new java.awt.Color(255, 255, 255));
        B_NAME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        B_NAME.setOpaque(true);
        jPanel2.add(B_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 460, 50));

        B_EMAIL.setBackground(new java.awt.Color(255, 255, 255));
        B_EMAIL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        B_EMAIL.setOpaque(true);
        jPanel2.add(B_EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 460, 50));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("مستفید کا نام");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 460, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("مستفید کے والد کا نام");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 460, 30));

        right.setBackground(new java.awt.Color(44, 80, 120));
        right.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Done.png"))); // NOI18N
        right.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightActionPerformed(evt);
            }
        });
        jPanel2.add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 50, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 920, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Fund_transfer ft = new Fund_transfer(CN);
        ft.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void amounttfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amounttfFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_amounttfFocusGained

    private void amounttfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amounttfFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_amounttfFocusLost

    private void rightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightActionPerformed
        // TODO add your handling code here:
        if("".equals(BNtf.getText().trim())){
            JOptionPane.showMessageDialog(this, "Please enter Cousumer Number", "Message", 1);
        }else{
            if(!BNtf.getText().trim().matches("\\d+")){
                JOptionPane.showMessageDialog(this, "Enter digits only", "Message", 1);
            }else{
                long BN = Long.parseLong(BNtf.getText().trim());
                SQL db = new SQL();
                ResultSet rs;
                rs = db.getaccount(BN);
                try {
                    if (rs.next()) {
                        B_NAME.setText(rs.getString("C_NAME"));
                        B_EMAIL.setText(rs.getString("C_EMAIL"));
                    }else{
                        JOptionPane.showMessageDialog(this, "User Not Found!", "Message", 1);
                        B_NAME.setText("");
                        B_EMAIL.setText("");
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_rightActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        ResultSet rs;
        int currentamount = 0;
        long BN = Long.parseLong(BNtf.getText());
        SQL db= new SQL();
        rs =db.balanceinquiry(CN);
        try {
            if(rs.next()){
                currentamount = rs.getInt("AMOUNT");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        
        if("".equals(BNtf.getText().trim())){
            JOptionPane.showMessageDialog(this, "Please enter Cousumer Number", "Message", 1);
        }else{
            if("".equals(amounttf.getText().trim())){
                JOptionPane.showMessageDialog(this, "Please enter amount", "Message", 1);
            }else{
                String amounttext = amounttf.getText().trim();
                if(!amounttext.matches("\\d+") || !BNtf.getText().trim().matches("\\d+")){
                    JOptionPane.showMessageDialog(this, "Enter digits only", "Message", 1);
                }else{
                    int cash = Integer.parseInt(amounttf.getText().trim());
                    if(cash <= 0){
                        JOptionPane.showMessageDialog(this, "Amount can not be ZERO or NEGATIVE", "Message", 1);
                    }else{
                        if(currentamount<cash){
                            JOptionPane.showMessageDialog(this, "Insufficient Amount", "Message", 1);
                        }else{
                            try{
                                if(db.withdraw(CN, cash)==1 && db.transfertransactions(CN, "Fund Transfer", cash, BNtf.getText().trim())==1 && db.deposit(BN, cash)==1){
                                    JOptionPane.showMessageDialog(this, "Withdraw Successful", "INFO", 1);
                                    amounttf.setText("");
                                    BNtf.setText("");
                                    B_NAME.setText("");
                                    B_EMAIL.setText("");
                                }else{
                                    JOptionPane.showMessageDialog(this, "Withdraw failed", "Error", 0);
                                }
                            }catch(Exception e){  
                                System.out.println(e);
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new btnaccount().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BNtf;
    private javax.swing.JLabel B_EMAIL;
    private javax.swing.JLabel B_NAME;
    private javax.swing.JTextField amounttf;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton ok;
    private javax.swing.JButton right;
    // End of variables declaration//GEN-END:variables
}
