/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bmsprojectcs2a;

/**
 *
 * @author Alienware 15T 4k
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    long CN;
    public Dashboard(long CN) {
        initComponents();
        this.CN = CN;
    }

    private Dashboard() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        deposit = new javax.swing.JButton();
        withdraw = new javax.swing.JButton();
        check_balance = new javax.swing.JButton();
        transfer = new javax.swing.JButton();
        billpayment = new javax.swing.JButton();
        mini_statement = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fastcash = new javax.swing.JButton();
        pinchange = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DASHBOARD");
        setSize(new java.awt.Dimension(1000, 800));
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(44, 80, 120));

        jPanel2.setBackground(new java.awt.Color(110, 148, 198));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Withdrawal Limit_1.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, 50, 50));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Dialing Number.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, 50, 50));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Money Transfer.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, 50, 50));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Euro Money.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 50, 50));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Purchase Order.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 50, 50));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Safe In.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 50, 50));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Bill.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 50, 50));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logout.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, 50, 50));

        jLabel11.setForeground(new java.awt.Color(110, 148, 198));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cash_1.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 50, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, -1, 70));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, -1, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please Select a Transaction");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 10, 470, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, -1, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, -1, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, -1, 70));

        deposit.setBackground(new java.awt.Color(44, 80, 120));
        deposit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deposit.setForeground(new java.awt.Color(255, 255, 255));
        deposit.setText("          Funds Deposit                 فنڈز ڈپازٹ");
        deposit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deposit.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositActionPerformed(evt);
            }
        });
        jPanel2.add(deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 300, 50));

        withdraw.setBackground(new java.awt.Color(44, 80, 120));
        withdraw.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        withdraw.setForeground(new java.awt.Color(255, 255, 255));
        withdraw.setText("Cash Withdrawal         نقد رقم کے لیے");
        withdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        withdraw.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawActionPerformed(evt);
            }
        });
        jPanel2.add(withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 300, 50));

        check_balance.setBackground(new java.awt.Color(44, 80, 120));
        check_balance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        check_balance.setForeground(new java.awt.Color(255, 255, 255));
        check_balance.setText("         Balance Inquiry         بیلنس انکوائری");
        check_balance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        check_balance.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        check_balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_balanceActionPerformed(evt);
            }
        });
        jPanel2.add(check_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 300, 50));

        transfer.setBackground(new java.awt.Color(44, 80, 120));
        transfer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        transfer.setForeground(new java.awt.Color(255, 255, 255));
        transfer.setText("Funds Transfer             رقم کی منتقلی");
        transfer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transfer.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });
        jPanel2.add(transfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 300, 50));

        billpayment.setBackground(new java.awt.Color(44, 80, 120));
        billpayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        billpayment.setForeground(new java.awt.Color(255, 255, 255));
        billpayment.setText("          Bill Payment              بل کی ادائیگی");
        billpayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        billpayment.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        billpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billpaymentActionPerformed(evt);
            }
        });
        jPanel2.add(billpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 300, 50));

        mini_statement.setBackground(new java.awt.Color(44, 80, 120));
        mini_statement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mini_statement.setForeground(new java.awt.Color(255, 255, 255));
        mini_statement.setText("          Mini Statement         منی اسٹیٹمنٹ");
        mini_statement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mini_statement.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        mini_statement.setPreferredSize(new java.awt.Dimension(75, 25));
        mini_statement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mini_statementActionPerformed(evt);
            }
        });
        jPanel2.add(mini_statement, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 300, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("برائے مہربانی مطلوبہ ٹرانزیکشن کا انتخاب کیجئے");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        fastcash.setBackground(new java.awt.Color(44, 80, 120));
        fastcash.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fastcash.setForeground(new java.awt.Color(255, 255, 255));
        fastcash.setText("فوری رقم نکالیں                    Fast Cash");
        fastcash.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fastcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastcashActionPerformed(evt);
            }
        });
        jPanel2.add(fastcash, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 300, 50));

        pinchange.setBackground(new java.awt.Color(44, 80, 120));
        pinchange.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pinchange.setForeground(new java.awt.Color(255, 255, 255));
        pinchange.setText("PIN Change                    پن کی تبدیلی");
        pinchange.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        pinchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinchangeActionPerformed(evt);
            }
        });
        jPanel2.add(pinchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 300, 50));

        exit.setBackground(new java.awt.Color(44, 80, 120));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("          Exit                                   رجوع کریں");
        exit.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 300, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositActionPerformed
        // TODO add your handling code here:
        Deposit dp = new Deposit(CN);
        dp.setVisible(true);
        dispose();
    }//GEN-LAST:event_depositActionPerformed

    private void withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawActionPerformed
        // TODO add your handling code here:
        Withdrawpage wp =new Withdrawpage(CN);
        wp.setVisible(true);
        dispose();
    }//GEN-LAST:event_withdrawActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
        // TODO add your handling code here:
        Fund_transfer ft= new Fund_transfer(CN);
        ft.setVisible(true);
        dispose();
    }//GEN-LAST:event_transferActionPerformed

    private void check_balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_balanceActionPerformed
        // TODO add your handling code here:
        BalanceInquirypage bi =new BalanceInquirypage(CN);
        bi.setVisible(true);
        dispose();
    }//GEN-LAST:event_check_balanceActionPerformed

    private void billpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billpaymentActionPerformed
        // TODO add your handling code here:
        Bill_payment bp = new Bill_payment(CN);
        bp.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_billpaymentActionPerformed

    private void mini_statementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mini_statementActionPerformed
        // TODO add your handling code here:
        MiniStatementpage msp = new MiniStatementpage(CN);
        msp.setVisible(true);
    }//GEN-LAST:event_mini_statementActionPerformed

    private void fastcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastcashActionPerformed
        // TODO add your handling code here:
        FastCash fc = new FastCash(CN);
        fc.setVisible(true);
        dispose();
    }//GEN-LAST:event_fastcashActionPerformed

    private void pinchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinchangeActionPerformed
        // TODO add your handling code here:
        PinChange pc = new PinChange(CN);
        pc.setVisible(true);
        dispose();
    }//GEN-LAST:event_pinchangeActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billpayment;
    private javax.swing.JButton check_balance;
    private javax.swing.JButton deposit;
    private javax.swing.JButton exit;
    private javax.swing.JButton fastcash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mini_statement;
    private javax.swing.JButton pinchange;
    private javax.swing.JButton transfer;
    private javax.swing.JButton withdraw;
    // End of variables declaration//GEN-END:variables
}
