/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bmsprojectcs2a;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Alienware 15T 4k
 */
public class FastCash extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FastCash.class.getName());

    /**
     * Creates new form FastCash
     */
    
    long CN;
    
    public FastCash(long CN) {
        initComponents();
        this.CN=CN;
        
    }

    private FastCash() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void processFastCash(int amount) {
    ResultSet rs;
    int currentamount = 0;
    SQL db= new SQL();
    rs=db.balanceinquiry(CN);
    try {
        if(rs.next()){
            currentamount = rs.getInt("AMOUNT");
        }
    } catch (Exception e) {
        System.out.println(e);
    }
    if (currentamount < amount) {
        JOptionPane.showMessageDialog(this, "Insufficient Balance", "Message", 0);
        return;
    }
    try {
        if (db.transactions(CN, "Fast Cash", amount) == 1 && db.withdraw(CN, amount) == 1) {
            JOptionPane.showMessageDialog(this, "Withdraw Successful", "INFO", 1);
        } else {
            JOptionPane.showMessageDialog(this, "Withdraw Failed", "Error", 0);
        }
    } catch (Exception e) {
        System.out.println(e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cash10000 = new javax.swing.JButton();
        cash5000 = new javax.swing.JButton();
        cash1000 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        cash200000 = new javax.swing.JButton();
        cash100000 = new javax.swing.JButton();
        cash50000 = new javax.swing.JButton();
        cash20000 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 80, 120));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(110, 148, 198));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setForeground(new java.awt.Color(110, 148, 198));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cash_1.png"))); // NOI18N
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 50, 50));

        jLabel24.setForeground(new java.awt.Color(110, 148, 198));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cash_1.png"))); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 50, 50));

        jLabel23.setForeground(new java.awt.Color(110, 148, 198));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cash_1.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 50, 50));

        jLabel22.setForeground(new java.awt.Color(110, 148, 198));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cash_1.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 50, 50));

        jLabel21.setForeground(new java.awt.Color(110, 148, 198));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cash_1.png"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 520, 50, 50));

        jLabel19.setForeground(new java.awt.Color(110, 148, 198));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cash_1.png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 50, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go Back_1.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 630, 50, 50));

        jLabel20.setForeground(new java.awt.Color(110, 148, 198));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cash_1.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, 50, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, -1, 70));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, -1, 70));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, 70));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, 70));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, 70));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, -1, 70));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, -1, 70));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, -1, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please select amount ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 360, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("براہِ مہربانی رقم کا انتخاب کیجئے");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 360, -1));

        cash10000.setBackground(new java.awt.Color(44, 80, 120));
        cash10000.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cash10000.setForeground(new java.awt.Color(255, 255, 255));
        cash10000.setText("RS. 10,000");
        cash10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash10000ActionPerformed(evt);
            }
        });
        jPanel2.add(cash10000, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 300, 50));

        cash5000.setBackground(new java.awt.Color(44, 80, 120));
        cash5000.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cash5000.setForeground(new java.awt.Color(255, 255, 255));
        cash5000.setText("RS. 5000");
        cash5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash5000ActionPerformed(evt);
            }
        });
        jPanel2.add(cash5000, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 300, 50));

        cash1000.setBackground(new java.awt.Color(44, 80, 120));
        cash1000.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cash1000.setForeground(new java.awt.Color(255, 255, 255));
        cash1000.setText("RS. 1000");
        cash1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash1000ActionPerformed(evt);
            }
        });
        jPanel2.add(cash1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 300, 50));

        back.setBackground(new java.awt.Color(44, 80, 120));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK                           پیچھے جائیں");
        back.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 630, 300, 50));

        cash200000.setBackground(new java.awt.Color(44, 80, 120));
        cash200000.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cash200000.setForeground(new java.awt.Color(255, 255, 255));
        cash200000.setText("RS. 200,000");
        cash200000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash200000ActionPerformed(evt);
            }
        });
        jPanel2.add(cash200000, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 300, 50));

        cash100000.setBackground(new java.awt.Color(44, 80, 120));
        cash100000.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cash100000.setForeground(new java.awt.Color(255, 255, 255));
        cash100000.setText("RS. 100,000");
        cash100000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash100000ActionPerformed(evt);
            }
        });
        jPanel2.add(cash100000, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 300, 50));

        cash50000.setBackground(new java.awt.Color(44, 80, 120));
        cash50000.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cash50000.setForeground(new java.awt.Color(255, 255, 255));
        cash50000.setText("RS. 50,000");
        cash50000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash50000ActionPerformed(evt);
            }
        });
        jPanel2.add(cash50000, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 300, 50));

        cash20000.setBackground(new java.awt.Color(44, 80, 120));
        cash20000.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cash20000.setForeground(new java.awt.Color(255, 255, 255));
        cash20000.setText("RS. 20,000");
        cash20000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash20000ActionPerformed(evt);
            }
        });
        jPanel2.add(cash20000, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, 300, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 935, 736));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1015, 816));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cash200000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash200000ActionPerformed
        // TODO add your handling code here:
        int amount = 200000;
        processFastCash(amount);
    }//GEN-LAST:event_cash200000ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Dashboard d= new Dashboard(CN);
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void cash1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash1000ActionPerformed
        // TODO add your handling code here:
        int amount = 1000;
        processFastCash(amount);
    }//GEN-LAST:event_cash1000ActionPerformed

    private void cash5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash5000ActionPerformed
        // TODO add your handling code here:
        int amount = 5000;
        processFastCash(amount);
    }//GEN-LAST:event_cash5000ActionPerformed

    private void cash10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash10000ActionPerformed
        // TODO add your handling code here:
        int amount = 10000;
        processFastCash(amount);
    }//GEN-LAST:event_cash10000ActionPerformed

    private void cash100000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash100000ActionPerformed
        // TODO add your handling code here:
        int amount = 100000;
        processFastCash(amount);
    }//GEN-LAST:event_cash100000ActionPerformed

    private void cash50000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash50000ActionPerformed
        // TODO add your handling code here:
        int amount = 50000;
        processFastCash(amount);
    }//GEN-LAST:event_cash50000ActionPerformed

    private void cash20000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash20000ActionPerformed
        // TODO add your handling code here:
        int amount = 20000;
        processFastCash(amount);
    }//GEN-LAST:event_cash20000ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FastCash().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton cash1000;
    private javax.swing.JButton cash10000;
    private javax.swing.JButton cash100000;
    private javax.swing.JButton cash20000;
    private javax.swing.JButton cash200000;
    private javax.swing.JButton cash5000;
    private javax.swing.JButton cash50000;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
