/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bmsprojectcs2a;

/**
 *
 * @author Alienware 15T 4k
 */
public class otheraccount extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(otheraccount.class.getName());

    /**
     * Creates new form FastCash
     */
    long CN;
    public otheraccount(long CN) {
        initComponents();
        this.CN=CN;
    }

    private otheraccount() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HMbank = new javax.swing.JButton();
        faisalbank = new javax.swing.JButton();
        islamibank = new javax.swing.JButton();
        back = new javax.swing.JButton();
        hblbank = new javax.swing.JButton();
        mcbbank = new javax.swing.JButton();
        alfalabank = new javax.swing.JButton();
        ublbank = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 80, 120));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(110, 148, 198));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setForeground(new java.awt.Color(110, 148, 198));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Bank Building_3.png"))); // NOI18N
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 50, 50));

        jLabel24.setForeground(new java.awt.Color(110, 148, 198));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Bank Building_3.png"))); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 50, 50));

        jLabel23.setForeground(new java.awt.Color(110, 148, 198));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Bank Building_3.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 50, 50));

        jLabel22.setForeground(new java.awt.Color(110, 148, 198));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Bank Building_3.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 50, 50));

        jLabel21.setForeground(new java.awt.Color(110, 148, 198));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Bank Building_3.png"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 520, 50, 50));

        jLabel19.setForeground(new java.awt.Color(110, 148, 198));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Bank Building_3.png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 50, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go Back_1.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 630, 50, 50));

        jLabel20.setForeground(new java.awt.Color(110, 148, 198));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Bank Building_3.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, 50, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 510, -1, 70));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, -1, 70));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, 70));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, 70));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, 70));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, -1, 70));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, -1, 70));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, -1, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please select amount ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 360, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("براہِ مہربانی رقم کا انتخاب کیجئے");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 360, -1));

        HMbank.setBackground(new java.awt.Color(44, 80, 120));
        HMbank.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HMbank.setForeground(new java.awt.Color(255, 255, 255));
        HMbank.setText("HABIB METRO Bank");
        HMbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HMbankActionPerformed(evt);
            }
        });
        jPanel2.add(HMbank, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 300, 50));

        faisalbank.setBackground(new java.awt.Color(44, 80, 120));
        faisalbank.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        faisalbank.setForeground(new java.awt.Color(255, 255, 255));
        faisalbank.setText("FAISAL Bank");
        faisalbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faisalbankActionPerformed(evt);
            }
        });
        jPanel2.add(faisalbank, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 300, 50));

        islamibank.setBackground(new java.awt.Color(44, 80, 120));
        islamibank.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        islamibank.setForeground(new java.awt.Color(255, 255, 255));
        islamibank.setText("Bank ISLAMI");
        islamibank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                islamibankActionPerformed(evt);
            }
        });
        jPanel2.add(islamibank, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 300, 50));

        back.setBackground(new java.awt.Color(44, 80, 120));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK                           پیچھے جائیں");
        back.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 630, 300, 50));

        hblbank.setBackground(new java.awt.Color(44, 80, 120));
        hblbank.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hblbank.setForeground(new java.awt.Color(255, 255, 255));
        hblbank.setText("HBL Bank");
        hblbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hblbankActionPerformed(evt);
            }
        });
        jPanel2.add(hblbank, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 300, 50));

        mcbbank.setBackground(new java.awt.Color(44, 80, 120));
        mcbbank.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mcbbank.setForeground(new java.awt.Color(255, 255, 255));
        mcbbank.setText("MCB Bank");
        mcbbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcbbankActionPerformed(evt);
            }
        });
        jPanel2.add(mcbbank, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 300, 50));

        alfalabank.setBackground(new java.awt.Color(44, 80, 120));
        alfalabank.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alfalabank.setForeground(new java.awt.Color(255, 255, 255));
        alfalabank.setText("ALAFALA Bank");
        alfalabank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfalabankActionPerformed(evt);
            }
        });
        jPanel2.add(alfalabank, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 300, 50));

        ublbank.setBackground(new java.awt.Color(44, 80, 120));
        ublbank.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ublbank.setForeground(new java.awt.Color(255, 255, 255));
        ublbank.setText("UBL Bank");
        ublbank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ublbankActionPerformed(evt);
            }
        });
        jPanel2.add(ublbank, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, 300, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 935, 736));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1015, 816));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hblbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hblbankActionPerformed
        // TODO add your handling code here:
        HBL_bank hbl = new HBL_bank(CN);
        hbl.setVisible(true);
        dispose();
    }//GEN-LAST:event_hblbankActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Fund_transfer ft= new Fund_transfer(CN);
        ft.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void mcbbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcbbankActionPerformed
        // TODO add your handling code here:
        MCB_bank mcb = new MCB_bank(CN);
        mcb.setVisible(true);
        dispose();
    }//GEN-LAST:event_mcbbankActionPerformed

    private void alfalabankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfalabankActionPerformed
        // TODO add your handling code here:
        ALFALA_Bank alfala = new ALFALA_Bank(CN);
        alfala.setVisible(true);
        dispose();
    }//GEN-LAST:event_alfalabankActionPerformed

    private void ublbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ublbankActionPerformed
        // TODO add your handling code here:
        UBL_bank ubl = new UBL_bank(CN);
        ubl.setVisible(true);
        dispose();
    }//GEN-LAST:event_ublbankActionPerformed

    private void HMbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HMbankActionPerformed
        // TODO add your handling code here:
        HABIBMETRO_bank habibmetro = new HABIBMETRO_bank(CN);
        habibmetro.setVisible(true);
        dispose();
    }//GEN-LAST:event_HMbankActionPerformed

    private void faisalbankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faisalbankActionPerformed
        // TODO add your handling code here:
        FAISAL_bank faisal = new FAISAL_bank(CN);
        faisal.setVisible(true);
        dispose();
    }//GEN-LAST:event_faisalbankActionPerformed

    private void islamibankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_islamibankActionPerformed
        // TODO add your handling code here:
        ISLAMI_bank islami = new ISLAMI_bank(CN);
        islami.setVisible(true);
        dispose();
    }//GEN-LAST:event_islamibankActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new otheraccount().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HMbank;
    private javax.swing.JButton alfalabank;
    private javax.swing.JButton back;
    private javax.swing.JButton faisalbank;
    private javax.swing.JButton hblbank;
    private javax.swing.JButton islamibank;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mcbbank;
    private javax.swing.JButton ublbank;
    // End of variables declaration//GEN-END:variables
}
