/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bmsprojectcs2a;

import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Alienware 15T 4k
 */
public class Water_bill extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Water_bill.class.getName());

    /**
     * Creates new form Withdrawpage
     */
    long CN;
    public Water_bill(long CN) {
        initComponents();
        this.CN = CN;
    }

    private Water_bill() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        C_NO = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        amounttf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WITHDRAW");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 80, 120));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(110, 148, 198));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Go Back_1.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 630, 50, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Checkmark_1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, 50, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, -1, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Filled Circle_1.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 620, -1, 70));

        C_NO.setBackground(new java.awt.Color(255, 255, 255));
        C_NO.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(C_NO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 460, 49));

        jButton1.setBackground(new java.awt.Color(44, 80, 120));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("  ہاں                             Ok");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, 250, 50));

        back.setBackground(new java.awt.Color(44, 80, 120));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back             پیچھے جائیں");
        back.setToolTipText("Go to Dashboard");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 630, 250, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please enter your Water-Bill consumer or reference number");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 650, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Please enter bill amount");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 650, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("براہِ کرم اپنے پانی کے بل کا کنزیومر یا ریفرنس نمبر درج کریں");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 650, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("بل کی رقم کا اندراج کریں");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 650, 40));

        amounttf.setBackground(new java.awt.Color(255, 255, 255));
        amounttf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        amounttf.setForeground(new java.awt.Color(0, 0, 0));
        amounttf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amounttfActionPerformed(evt);
            }
        });
        jPanel2.add(amounttf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 460, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 920, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Bill_payment bp = new Bill_payment(CN);
        bp.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ResultSet rs;
        int currentamount = 0;
        
        SQL db= new SQL();
        rs =db.balanceinquiry(CN);
        try {
            if(rs.next()){
                currentamount = rs.getInt("AMOUNT");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        
        if("".equals(C_NO.getText().trim())){
            JOptionPane.showMessageDialog(this, "Please enter Cousumer Number", "Message", 1);
        }else{
            if("".equals(amounttf.getText().trim())){
                JOptionPane.showMessageDialog(this, "Please enter amount", "Message", 1);
            }else{
                String amounttext = amounttf.getText().trim();
                if(!amounttext.matches("\\d+") || !C_NO.getText().trim().matches("\\d+")){
                    JOptionPane.showMessageDialog(this, "Enter digits only", "Message", 1);
                }else{
                    int cash = Integer.parseInt(amounttf.getText().trim());
                    if(cash <= 0){
                        JOptionPane.showMessageDialog(this, "Amount can not be ZERO or NEGATIVE", "Message", 1);
                    }else{
                        if(currentamount<cash){
                            JOptionPane.showMessageDialog(this, "Insufficient Amount", "Message", 1);
                        }else{
                            String CNO=C_NO.getText().trim();
                            try{
                                if(db.withdraw(CN, cash)==1 && db.billtransactions(CN,"Water Bill", cash,CNO)==1){
                                    JOptionPane.showMessageDialog(this, "Payment Successful", "INFO", 1);
                                    amounttf.setText("");
                                    C_NO.setText("");
                                }else{
                                    JOptionPane.showMessageDialog(this, "Payment failed", "Error", 0);
                                }
                            }catch(Exception e){  
                                System.out.println(e);
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void amounttfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amounttfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amounttfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Water_bill().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C_NO;
    private javax.swing.JTextField amounttf;
    private javax.swing.JButton back;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
