/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cemetrysystem;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author parwani's
 */
public class burialchristian extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(burialchristian.class.getName());

    /**
     * Creates new form burialmuslim
     */
    int did;
    String dname;
    String dcnic;
    public burialchristian(int did,String dname,String dcnic) {
        initComponents();
        this.did = did;
        this.dname = dname;
        this.dcnic = dcnic;
        loadVisualPlots();
    }
private void loadVisualPlots() {

    visualPanel.removeAll();

    sql_model db = new sql_model();
    ResultSet rs = db.getplotrecordsc(); 

    try {
        while (rs.next()) {

            String plot = rs.getString("PLOT_NO");
            String sectionNo = rs.getString("SECTION_NO");
            String status = rs.getString("STATUS");

            JButton box = new JButton(
                "<html><center><b>Plot:</b> " + plot +
                "<br><b>Section:</b> " + sectionNo + "</center></html>"
            );

            box.setFont(new java.awt.Font("Segoe UI", 1, 12));
            box.setFocusPainted(false);

            if (status.equalsIgnoreCase("Available")) {
                box.setBackground(Color.GREEN);
            } else {
                box.setBackground(Color.RED);
                box.setEnabled(false);
            }

            box.addActionListener(e -> {
                plotno.setText(plot);
                section.setText(sectionNo);
            });

            visualPanel.add(box);
        }

    } catch (Exception e) {
        System.out.println(e);
    }

    visualPanel.revalidate();
    visualPanel.repaint();
}
    private burialchristian() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        plotno = new javax.swing.JTextField();
        section = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        length = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        width = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        visualPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        depth = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Plot Selection");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Plot Number:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Block / Section:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Burial Date:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Width:");

        plotno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        plotno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                plotnoKeyPressed(evt);
            }
        });

        section.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        section.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sectionKeyPressed(evt);
            }
        });

        date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        date.setForeground(new java.awt.Color(153, 153, 153));
        date.setText("YYYY-MM-DD");
        date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateFocusLost(evt);
            }
        });
        date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dateKeyPressed(evt);
            }
        });

        length.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        length.setForeground(new java.awt.Color(153, 153, 153));
        length.setText("In ft");
        length.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lengthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lengthFocusLost(evt);
            }
        });
        length.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lengthKeyPressed(evt);
            }
        });

        next.setBackground(new java.awt.Color(0, 123, 255));
        next.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Plot Availability");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemetrysystem/icon/icons8_ground_50px.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Length:");

        width.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        width.setForeground(new java.awt.Color(153, 153, 153));
        width.setText("In ft");
        width.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                widthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                widthFocusLost(evt);
            }
        });
        width.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                widthKeyPressed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(0, 123, 255));
        cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        visualPanel.setBackground(new java.awt.Color(255, 255, 255));
        visualPanel.setLayout(new java.awt.GridLayout(4, 5));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\parwani's\\Pictures\\grave1.PNG")); // NOI18N
        jLabel10.setText("jLabel10");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Depth:");

        depth.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        depth.setForeground(new java.awt.Color(153, 153, 153));
        depth.setText("In ft");
        depth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                depthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                depthFocusLost(evt);
            }
        });
        depth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                depthKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(plotno, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(depth, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(next, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(visualPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plotno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(section, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(visualPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        String datePattern ="^(19[0-9]{2}|20[0-1][0-9]|202[0-5])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$";
        Pattern pd = Pattern.compile(datePattern);
        Matcher md = pd.matcher(date.getText());
        
        String measurepattern = "^[0-9]+(\\.[0-9]+)?$";
        Pattern pn = Pattern.compile(measurepattern);

        Matcher mlength = pn.matcher(length.getText());
        Matcher mwidth  = pn.matcher(width.getText());
        Matcher mdepth  = pn.matcher(depth.getText());
        
        if(plotno.getText().equals("")||section.getText().equals("")||date.getText().equals("YYYY/MM/DD")||length.getText().equals("")||width.getText().equals("")||depth.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Missing Details","ERROR",2);
            return;
        } 
       
        if (!md.matches()) {
            JOptionPane.showMessageDialog(this,"Invalid Date format (YYYY-MM-DD)","ERROR",2);
            return;
        }
        
        if (!mlength.matches()) {
            JOptionPane.showMessageDialog(this, "Invalid Length");
            return;
        }
        else if (!mwidth.matches()) {
            JOptionPane.showMessageDialog(this, "Invalid Width");
            return;
        }
        else if (!mdepth.matches()) {
            JOptionPane.showMessageDialog(this, "Invalid Depth");
            return;
        }
        
        sql_model db = new sql_model();
        try{
            int gidc = db.AddBurialC(did,plotno.getText(),section.getText(),date.getText(),length.getText(),width.getText(),depth.getText());
            if(gidc != -1){
                JOptionPane.showMessageDialog(this,"Plot Added Successfully!","SUCCESS",1);
                db.updatestatus(plotno.getText(), section.getText());
                loadVisualPlots();
                payment p = new payment(did, gidc,dname,dcnic,plotno.getText(),section.getText());
                p.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(this,"Alert","ERROR",0);
            }
        }catch(Exception e){
          System.out.println(e);
        }

        
    }//GEN-LAST:event_nextActionPerformed

    private void dateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFocusGained
        // TODO add your handling code here:
        if(date.getText().equals("YYYY-MM-DD")){
            date.setText("");
            date.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_dateFocusGained

    private void dateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFocusLost
        // TODO add your handling code here:
        if(date.getText().equals("")){
            date.setText("YYYY-MM-DD");
            date.setForeground(new Color(153,153,153));
        } 
    }//GEN-LAST:event_dateFocusLost

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        sql_model db = new sql_model();
        try{
            if(db.cancelRegistration(did)==1){
                JOptionPane.showMessageDialog(this,"Registration Cancelled","Alert",1 );
                dashboard d= new dashboard();
                d.setVisible(true);
                dispose();  
               System.out.println(did);
            }
        }catch(Exception e){
            System.out.println(e);
        }       
    }//GEN-LAST:event_cancelActionPerformed
    
    private void lengthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lengthFocusGained
        // TODO add your handling code here:
        if(length.getText().equals("In ft")){
            length.setText("");
            length.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_lengthFocusGained

    private void lengthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lengthFocusLost
        // TODO add your handling code here:
        if(length.getText().equals("")){
            length.setText("In ft");
            length.setForeground(new Color(153,153,153));
        } 
    }//GEN-LAST:event_lengthFocusLost

    private void widthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_widthFocusGained
        // TODO add your handling code here:
        if(width.getText().equals("In ft")){
            width.setText("");
            width.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_widthFocusGained

    private void widthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_widthFocusLost
        // TODO add your handling code here:
        if(width.getText().equals("")){
            width.setText("In ft");
            width.setForeground(new Color(153,153,153));
        } 
    }//GEN-LAST:event_widthFocusLost

    private void plotnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_plotnoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            section.requestFocus();
    }//GEN-LAST:event_plotnoKeyPressed

    private void sectionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sectionKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            date.requestFocus();
    }//GEN-LAST:event_sectionKeyPressed

    private void dateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            length.requestFocus();
    }//GEN-LAST:event_dateKeyPressed

    private void lengthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lengthKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            width.requestFocus();
    }//GEN-LAST:event_lengthKeyPressed

    private void widthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_widthKeyPressed
        // TODO add your handling if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            depth.requestFocus();
    }//GEN-LAST:event_widthKeyPressed

    private void depthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_depthFocusGained
        // TODO add your handling code here:
        if(depth.getText().equals("In ft")){
            depth.setText("");
            depth.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_depthFocusGained

    private void depthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_depthFocusLost
        // TODO add your handling code here:
        if(depth.getText().equals("")){
            depth.setText("In ft");
            depth.setForeground(new Color(153,153,153));
        } 
    }//GEN-LAST:event_depthFocusLost

    private void depthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depthKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_depthKeyPressed
                                    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new burialchristian().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField date;
    private javax.swing.JTextField depth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField length;
    private javax.swing.JButton next;
    private javax.swing.JTextField plotno;
    private javax.swing.JTextField section;
    private javax.swing.JPanel visualPanel;
    private javax.swing.JTextField width;
    // End of variables declaration//GEN-END:variables
}
