/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cemetrysystem;

import java.awt.Color;

/**
 *
 * @author parwani's
 */
public class dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboard.class.getName());

    /**
     * Creates new form login
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        add_deceased = new javax.swing.JButton();
        search = new javax.swing.JButton();
        manage_grave = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Dashboard");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 40, -1, -1));

        add_deceased.setBackground(new java.awt.Color(0, 123, 255));
        add_deceased.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add_deceased.setForeground(new java.awt.Color(255, 255, 255));
        add_deceased.setText("Add Deceased");
        add_deceased.setAlignmentX(40.0F);
        add_deceased.setAlignmentY(80.0F);
        add_deceased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_deceasedActionPerformed(evt);
            }
        });
        jPanel1.add(add_deceased, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 173, 170, 40));

        search.setBackground(new java.awt.Color(0, 123, 255));
        search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Records");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 255, 170, 40));

        manage_grave.setBackground(new java.awt.Color(0, 123, 255));
        manage_grave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manage_grave.setForeground(new java.awt.Color(255, 255, 255));
        manage_grave.setText("Manage Graves");
        manage_grave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_graveActionPerformed(evt);
            }
        });
        jPanel1.add(manage_grave, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 337, 170, 40));

        logout.setBackground(new java.awt.Color(0, 123, 255));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 419, 170, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemetrysystem/icon/icons8_login_rounded_right_30px_1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 30, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemetrysystem/icon/icons8_add_30px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 170, 30, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemetrysystem/icon/icons8_admin_settings_male_24px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 30, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemetrysystem/icon/icons8_dossier_24px.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 30, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\parwani's\\Pictures\\grave1.PNG")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 570, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_deceasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_deceasedActionPerformed
        // TODO add your handling code here:
        addeceased a = new addeceased();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_add_deceasedActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        search s = new search();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_searchActionPerformed

    private void manage_graveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_graveActionPerformed
        // TODO add your handling code here:
        managegrave m = new managegrave();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_manage_graveActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        login l = new login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_deceased;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton manage_grave;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
