/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cemetrysystem;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author parwani's
 */
public class search extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(search.class.getName());

    /**
     * Creates new form search
     */
    public search() {
        initComponents();
        sql_model db = new sql_model();
        ResultSet rs = db.showRecords();
        DefaultTableModel tb = (DefaultTableModel) record.getModel();
        tb.setRowCount(0);

        try {
            while(rs.next()){
                String data[] = {rs.getString("NAME"),rs.getString("CNIC"),rs.getString("CONTACT"),rs.getString("D_NAME"),rs.getString("D_CNIC_B_FORM"),rs.getString("PLOT_NO"),rs.getString("SECTION_NO"),rs.getString("AMOUNT"),rs.getString("created_date"),rs.getString("created_time"),};
                tb.addRow(data);
            }
        } catch (SQLException ex) {
            System.getLogger(search.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        record = new javax.swing.JTable();
        btnserach = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Search Records");

        search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        record.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "User CNIC", "User Contact", "Deceased Name", "Deceased CNIC", "Plot No", "Section", "Amount Paid", "Date", "Time"
            }
        ));
        jScrollPane1.setViewportView(record);
        if (record.getColumnModel().getColumnCount() > 0) {
            record.getColumnModel().getColumn(0).setPreferredWidth(10);
            record.getColumnModel().getColumn(1).setPreferredWidth(10);
            record.getColumnModel().getColumn(2).setPreferredWidth(10);
            record.getColumnModel().getColumn(3).setPreferredWidth(15);
            record.getColumnModel().getColumn(4).setPreferredWidth(15);
            record.getColumnModel().getColumn(5).setPreferredWidth(10);
            record.getColumnModel().getColumn(6).setPreferredWidth(10);
            record.getColumnModel().getColumn(7).setPreferredWidth(15);
            record.getColumnModel().getColumn(8).setPreferredWidth(5);
            record.getColumnModel().getColumn(9).setPreferredWidth(5);
        }

        btnserach.setBackground(new java.awt.Color(0, 123, 255));
        btnserach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnserach.setForeground(new java.awt.Color(255, 255, 255));
        btnserach.setText("Search");
        btnserach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnserachActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cemetrysystem/icon/icons8_circled_left_24px.png"))); // NOI18N
        back.setBorder(null);
        back.setContentAreaFilled(false);
        back.setFocusPainted(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(524, 524, 524)
                        .addComponent(btnserach, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnserach, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        dashboard d = new dashboard();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void btnserachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnserachActionPerformed
        // TODO add your handling code here:
        sql_model db= new sql_model();
        ResultSet rs;
        rs=db.searchRecords((search.getText()));
        DefaultTableModel tb= (DefaultTableModel)record.getModel();
        tb.setRowCount(0);
        try{
            while(rs.next()){
                String data[] = {rs.getString("NAME"),rs.getString("CNIC"),rs.getString("CONTACT"),rs.getString("D_NAME"),rs.getString("D_CNIC_B_FORM"),rs.getString("PLOT_NO"),rs.getString("SECTION_NO"),rs.getString("AMOUNT"),rs.getString("created_date"),rs.getString("created_time"),};
                tb.addRow(data);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnserachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new search().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnserach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable record;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
